from Funcion_3 import*
Nombre_del_empleado=str(input("Ingrese el nombre del empleado: "))
Sueldo_por_hora=float(input("Ingrese el sueldo por hora: "))
Numero_de_horas_trabajadas=float(input("Ingrese el numero de horas trabajadas: "))
Factor_de_exoneracion=float(input("Ingrese el factor de exoneracion: "))
Sb=Salario_bruto(Sueldo_por_hora,Numero_de_horas_trabajadas)
SSO=SSO(Sb)
Impuesto=Impuesto(Sb,Factor_de_exoneracion)
Sn=Sueldo_neto(Sb,SSO,Impuesto)
print("El nombre del empleado es: ",Nombre_del_empleado)
print("El numero de horas que trabajo es: ",Numero_de_horas_trabajadas)
print("El salario bruto del empleado",Nombre_del_empleado,"es: ",Sb)
print("El salario neto del empleado",Nombre_del_empleado,"es: ",Sn)
print("El Seguro social obligatorio(SSO)es de: ",SSO)