from Funcion_2 import*
Nombre_del_empleado=str(input("Ingrese el nombre del empleado: "))
Sueldo_base=float(input("Ingrese el sueldo base del empleado: "))
Numero_de_horas_trabajadas=float(input("Ingrese el numero de horas trabajadas durante la semana: "))
Valor_de_la_hora=float(input("Ingrese el valor de la hora: "))
PPHE=Pago_por_horas_extra(Numero_de_horas_trabajadas,Valor_de_la_hora)
P_n=Pago_neto(PPHE,Numero_de_horas_trabajadas,Valor_de_la_hora,Sueldo_base)
print("El Nombre del empleado es: ",Nombre_del_empleado)
print("El pago por horas extra es: ",PPHE)
print("El sueldo neto del empleado",Nombre_del_empleado,"es: ",P_n)